stages:
  - test
  - build

default:
  image: gameci/unity-builder:2022.3.0f1-webgl-3
  before_script:
    - mkdir -p /root/.local/share/unity3d/Unity/
    - cp "$UNITY_LICENSE" /root/.local/share/unity3d/Unity/Unity_lic.ulf

.unity_cache:
  cache:
    key: "Library-$CI_COMMIT_REF_SLUG"
    paths:
      - Library/

# 1. Запуск тестов (PlayMode & EditMode)
test-playmode:
  stage: test
  extends: .unity_cache
  script:
    - unity-builder --testMode playmode
  artifacts:
    when: always
    paths:
      - playmode-artifacts/

test-editmode:
  stage: test
  extends: .unity_cache
  script:
    - unity-builder --testMode editmode
  artifacts:
    when: always
    paths:
      - editmode-artifacts/

# 2. Сборка проекта под StandaloneWindows64
build-windows:
  stage: build
  extends: .unity_cache
  needs:
    - test-playmode
    - test-editmode
  script:
    - unity-builder --targetPlatform StandaloneWindows64
  artifacts:
    paths:
      - build/StandaloneWindows64/